### PR TITLE
Cross-compiled arm64-linux native extension (#15)

### LINKED ISSUE #9: Compile Linux arm64 version
- https://github.com/metanorma/metanorma-docker/runs/5560998536?check_suite_focus=true

### PR DESCRIPTION
**Pull request by maxirmx**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

Cross-compiled arm64-linux native extension

Co-authored-by: Alexande B <abobrikovich@gmail.com>

### CODE REVIEW

**Review by CAMOBAP — APPROVED** [review]
LGTM

**Review by ronaldtse — APPROVED** [review]
Thank you @maxirmx !

**Comment by ronaldtse** [comment]
And of course thank you @CAMOBAP !

**Comment by maxirmx** [comment]
image

**Pull request merged**
