### PR TITLE
#9 Add Aarch64 precompiled gem

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #9

### CODE REVIEW

**Comment by maxirmx** [comment]
@CAMOBAP 
There were some major issues with Windows build libemf2svg. One of dependencies just disappered from GitHub and also we hit vcpkg error.

https://github.com/metanorma/libemf2svg/issues/21

I can fix Windows workflow if you are OK with it

**Comment by ronaldtse** [comment]
@maxirmx yes please, it would be great if you can help fix this. Thanks!

**Comment by CAMOBAP** [comment]
@maxirmx to be on the same page, aarch64 which I added to matrix doesn't produce actual arm binary. I didn't look in deep, but looks like it builds only for the target platform. Probably  we need to use something similar to https://github.com/lutaml/expressir/blob/main/rakelib/cross-ruby.rake

**Comment by maxirmx** [comment]
@CAMOBAP Thank you, Alex
I was fixing broken Windows build.  Now when I have it working, I will look into aarch64.
(I attempted to use cross-compilation of native extensions in tenako project and now I understand that straightforwards approaches do not work.

**Comment by maxirmx** [comment]
Replaced by #16

**Pull request closed without merging**
