### PR TITLE
#21 fix platform name for arm64-linux prebuilt gem

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #21

### CODE REVIEW

**Review by maxirmx — APPROVED** [review]
The list in the Rakefile defines the triplets that can be used.  After that it gets translated to vcpkg-triplet in https://github.com/metanorma/emf2svg-ruby/blob/main/lib/emf2svg/recipe.rb

yaml files define the tags to publish only.
So your change is (1) publish as aarch64-linux   (2) disallow all other triplets

**Comment by ronaldtse** [comment]
@maxirmx I couldn't tell whether your approval is an approval 😉 . Does that mean you would approach the change in a different way? This gem clearly should be compiled for multiple platforms. e.g. `arm64-linux` clearly exists.

**Comment by CAMOBAP** [comment]
> (2) disallow all other triplets 

Yep, bundler will never resolve such platforms:

 - "arm64-osx",
   "aarch64-darwin",
   "arm64-macos",
   "aarch64-macos",

 - "x86_64-macos",
   "x86_64-osx",
   "aarch64-osx",

And my proposal is to remove them (I understand that those values are valid for `vcpkg`, but we have a special function to do the conversion)

Probably we need to clean this logic https://github.com/metanorma/emf2svg-ruby/blob/main/lib/emf2svg/recipe.rb#L59 to handle only valid platform values

> This gem clearly should be compiled for multiple platforms. e.g. arm64-linux clearly exists.

That's true and the correct platform name for `arm64-linux` is `aarch64-linux`. We can check nokogiri as reference for platform naming https://rubygems.org/gems/nokogiri/versions

**Comment by maxirmx** [comment]
> @maxirmx I couldn't tell whether your approval is an approval 😉 . Does that mean you would approach the change in a different way? This gem clearly should be compiled for multiple platforms. e.g. `arm64-linux` clearly exists.

@ronaldtse My approval is the approval if the behavior that I have described is the desired behavior.
- 'platform' in YAML files define the tag (triplet) the is used to publish native extension
- The list of platforms in the Rakefile defines the triplets that are supported.  Actual processesing is implemented in recipe.rb 
So this change will publish aarch64-linux instead of arm64-linux  and will limit the list of triplets.  

There is a separate issue related to libemf2svg dependencies (specified in the README https://github.com/metanorma/libemf2svg)
They are resolved by recipe.rb through vcpkg on Windows platform and in case of cross-compilation but are not resolved by recipe.rb in case of native Linux or MacOS compilation.

**Comment by CAMOBAP** [comment]
Thanks @maxirmx merging

**Pull request merged**
