### PR TITLE
libemf2svg version upgrade, Windows 2022/MS Visual Studio 2022/Ruby 3.1 support

### LINKED ISSUE #7: Build x64-mingw-ucrt version to support Windows Ruby 3.1
As per https://github.com/metanorma/isodoc/issues/385 the x64-mingw32 version is not compatible with Ruby 3.1 Windows.

We need to precompile a `x64-mingw-ucrt` version to allow Ruby 3.1 Windows to install this gem.

As described by @maxirmx https://github.com/metanorma/isodoc/issues/385#issuecomment-1067648062

> emf2svg build script explicitly references `MS Visual Studio 2019`  That was/is relevant for `Windows Server 2019` GHA runner
> Now `windows-latest` is `Windows Server 2022` that has `MS Visual Studio 2022`
> That's why build step fails

The value `Visual Studio 2019` is currently hard-coded here:
https://github.com/metanorma/emf2svg-ruby/blob/4d7d99717f1daefba73a18da3b5b5c693f7edc82/lib/emf2svg/recipe.rb#L42

We need to relax that to make this work.

### PR DESCRIPTION
**Pull request by maxirmx**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by maxirmx** [comment]
This PR will resolve various small issues related to support of new Windows/VS/Ruby version
The failing job tests  x86-migw-ucrt prebuilt extension whuch is not at rubygems.org yet

Release sequence is
- merge this PR
- publish release (it will trigger workflow that publush to rubygems.org)
- rerun test jobs

I need some review and advise about mfa that I do not fully understand

Thank you

**Comment by ronaldtse** [comment]
Thank you @maxirmx !

**Comment by ronaldtse** [comment]
The error about `gem install --no-document pkg/emf2svg-*-x64-ucrt.gem` is very strange because it is not supposed to fetch from rubygems.org, it is supposed to install a locally present gem.

**Comment by ronaldtse** [comment]
Ah, it's supposed to be `gem install --local path_to_gem/filename.gem`.

**Pull request merged**
